version: 0.2

# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
#   git-credential-helper: no | yes

        
phases:
  install:
    commands:
  build:
    commands:
       - docker build -t haseebpython .
       - docker save -o haseebpython.tar haseebpython
 artifacts:
   files:
     - 'haseebpython.tar'
   name: haseebpython
